version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nimbus
      - POSTGRES_USER=nimbus
      - POSTGRES_PASSWORD=nimbus
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gateway:
    build: ./backend/gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - identity-service
      - catalog-service
      - order-service
      - settings-service

  identity-service:
    build: ./backend/identity-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - JWT_SECRET=local-dev-secret-change-this-please-32chars
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nimbus
      - DB_USER=nimbus
      - DB_PASSWORD=nimbus

  catalog-service:
    build: ./backend/catalog-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - JWT_SECRET=local-dev-secret-change-this-please-32chars
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nimbus
      - DB_USER=nimbus
      - DB_PASSWORD=nimbus

  order-service:
    build: ./backend/order-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      - JWT_SECRET=local-dev-secret-change-this-please-32chars
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nimbus
      - DB_USER=nimbus
      - DB_PASSWORD=nimbus
      - CATALOG_SERVICE_URL=http://catalog-service:8082

  settings-service:
    build: ./backend/settings-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      - JWT_SECRET=KheMny@n3leL3b0n@
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nimbus
      - DB_USER=nimbus
      - DB_PASSWORD=nimbus

volumes:
  postgres-data:
