version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mynewpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  discovery-service:
    build: ./backend/discovery-service
    ports:
      - "8761:8761"

  gateway:
    build: ./backend/gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka
      - IDENTITY_SERVICE_URL=lb://identity-service
      - CATALOG_SERVICE_URL=lb://catalog-service
      - ORDER_SERVICE_URL=lb://order-service
      - SETTINGS_SERVICE_URL=lb://settings-service
    depends_on:
      - discovery-service
      - identity-service
      - catalog-service
      - order-service
      - settings-service

  identity-service:
    build: ./backend/identity-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - postgres
    environment:
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka
      - JWT_SECRET=identity5ecr3t31@
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mynewpassword

  catalog-service:
    build: ./backend/catalog-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - postgres
    environment:
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka
      - JWT_SECRET=identity5ecr3t31
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mynewpassword

  order-service:
    build: ./backend/order-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - postgres
    environment:
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka
      - JWT_SECRET=oderserviseserc3t1@
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mynewpassword
      - CATALOG_SERVICE_URL=http://catalog-service

  settings-service:
    build: ./backend/settings-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - postgres
    environment:
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka
      - JWT_SECRET=settings5ecr3tk3y
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mynewpassword

volumes:
  postgres-data:
