server:
  port: 8083

jwt:
  secret: oderserviseserc3t1@

catalog:
  base-url: http://localhost:8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mynewpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgresqlDialect 
  jackson:
    serialization:
      write-dates-as-timestamps: false
