server:
  port: 8084

jwt:
  secret: settings5ecr3tk3y

spring:
  application:
    name: settings-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mynewpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect 
  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
